### ISSUE TITLE
3D plot truncated or wrongly meshed?

### ISSUE THREAD

**Issue by dvanderelst** [bfroehle/pydistmesh#15]
When running the 3D examples, the first plot coming up is that of a meshed sphere. The plot seems incorrect (see image). The points generated seem ok. I can run the code to mesh a sphere and generate a scatter plot of the points that look indeed like a sphere.

Is this the intendened behavior?

![Figure_1](https://user-images.githubusercontent.com/34309937/63654295-bcc25000-c746-11e9-8e59-f079ab4d8607.png)
.

**Comment by popersson** [comment]
Yes this is intended... in order to get a rough view on what the elements look like inside of the sphere, a cut is made and the interior tetrahedra are shown in purple. The location of the cut is in this case given by the expression x>0, and this is not available as a function argument but you can manually change the line:

  axes_simpplot3d(ax, p, t, p[:,1] > 0)

If you only want to see the outside of the mesh, you can change p[:,1] > 0 to the default value None.

**Comment by dvanderelst** [comment]
ok. I wasn't sure about that. Closing the "issue".
